language: c

sudo: false

addons:
  apt:
    packages:
      - libev-dev
      - libssl-dev

before_script:
  - ./bootstrap
  - ./configure --prefix=/usr
  - make -j4

script:
#  - make check -j4
  - cd tests && ./runtests

compiler:
  - clang
  - gcc



