language: c

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq libev-dev libssl-dev automake python-docutils flex bison


before_script:
  - ./bootstrap
  - ./configure --prefix=/usr
  - make -j4

script:
#  - make check -j4
  - ./src/tests/runtests

compiler:
  - clang
  - gcc
